---
title: "p8105_hw5_jh4054"
author: "Joy Hsu"
date: "11/5/2018"
output: html_document
---

### 0. Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(rvest)
library(knitr)

set.seed(1)

knitr::opts_chunk$set(
  collapse = TRUE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))
```

### Problem 1
```{r}
#tidy dataset
patient_df = 
  tibble(
    id = c(str_c("con_0", 01:9), "con_10", str_c("exp_0", 01:9), "exp_10"),
    csv = list.files("./data", full.names = TRUE),
    data = map(csv, read_csv)) %>% 
  unnest() %>% 
  janitor::clean_names() %>% 
  gather(key = week, value = observation, week_1:week_8) %>% 
  mutate(week = str_replace(week, "week_", ""),
         arm = str_replace(id, "_..", ""),
         id = str_replace(id, "..._", ""),
         week = as.integer(as.factor(week)),
         id = as.factor(id)) %>% 
  select(arm, id, week, observation) %>%
  arrange(arm, id, week)

#spaghetti plot
patient_plot = patient_df %>% 
  group_by(id) %>% 
  ggplot(aes(x = week, y = observation, color = id)) +
  geom_line() +
  facet_grid(~arm) +
  viridis::scale_color_viridis(discrete = TRUE)
patient_plot

#linear model
lm_exp = lm(week ~ observation, data = filter(patient_df, arm == "exp")) %>% broom::tidy() %>% mutate(sig = p.value < 0.05)
lm_con = lm(week ~ observation, data = filter(patient_df, arm == "con")) %>% broom::tidy() %>% mutate(sig = p.value < 0.05)
```

```{r}
#Method 2: provide a character vector of the names of files in named directory data
patient_id2 = 
  tibble(
    id = c(str_c("con_0", 01:9), "con_10", str_c("exp_0", 01:9), "exp_10")) %>%
  mutate(csv = str_c("./data/", id, ".csv")) 
  
patient_df2 = patient_id %>% 
  mutate(observation = map(patient_id$csv, read_csv)) %>% 
  unnest() %>% 
  janitor::clean_names() %>% 
  gather(key = week, value = observation, week_1:week_8) %>% 
  mutate(week = str_replace(week, "week_", ""),
         arm = str_replace(id, "_..", ""),
         id = str_replace(id, "..._", ""),
         week = as.integer(as.factor(week)),
         id = as.factor(id)) %>% 
  select(arm, id, week, observation) %>%
  arrange(arm, id, week)
```

### Problem 2

Load and clean dataset
```{r}
#load and tidy dataset
homicide_data = read_csv("./data/homicide-data.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    city_state = str_c(city, ", ", state),
    city_state = str_replace(city_state, "Tulsa, AL", "Tulsa, OK"),
    hom_unsolved = ifelse(disposition != "Closed by arrest", 1, 0))

#total homicides
homicide_total = homicide_data %>% 
  group_by(city_state) %>% 
  summarise(hom_total = n())

#total unsolved homicides
homicide_unsolve = homicide_data %>% 
  group_by(city_state) %>% 
  summarise(hom_unsolved = sum(hom_unsolved))

#total number of homicides and unsolved homicides
homicide_tidy = left_join(homicide_total, homicide_unsolve)
```

prop.test for baltimore
```{r}
prop_test_baltimore = homicide_tidy %>% 
  filter(city_state == "Baltimore, MD") %>% 
  with(., prop.test(n = hom_total, x = hom_unsolved)) %>% 
  broom::tidy() %>% 
  select(estimate, conf.low, conf.high)
prop_test_baltimore %>% kable(digits = 2)
```


prop.test for other cities
```{r}
prop_test_all = homicide_tidy %>% 
  mutate(prop = map2(.x = hom_total, .y = hom_unsolved, ~prop.test(n = .x, x = .y)),
         prop = map(prop, broom::tidy)) %>% 
  unnest() %>% 
  select(city_state, estimate, conf.low, conf.high) %>% 
  mutate(city_state = fct_reorder(city_state, estimate))

  
map2(.x = hom_total, .y = hom_unsolved, ~prop.test(n = .x, x = .y))

prop_test_balt = homicide_tidy %>% 
  filter(city_state == "Baltimore, MD") %>% 
  mutate(prop = map2(data, .x = hom_total, .y = hom_unsolved, ~prop.test(n = .x, x = .y)),
         prop = map(prop, broom::tidy)) %>%
  unnest() %>% unnest()

prop_test_balt = homicide_tidy %>% 
  filter(city_state == "Baltimore, MD") %>% 
  group_by(city_state) %>% 
  nest() %>% 
  mutate(prop = map2(data, .x = hom_total, .y = hom_unsolved, ~prop.test(n = .x, x = .y)),
         prop = map(prop, broom::tidy)) %>%
  unnest()


p1 = homicide_tidy %>% 
  filter(city_state == "Baltimore, MD") %>% 
  mutate(prop = map2(hom_total, hom_unsolved, ~prop.test)) %>% 
  broom::tidy() %>% 
  unnest()

prop.test(n = homicide_tidy$hom_total, x = homicide_tidy$hom_unsolved)



prop_test_baltimore = homicide_tidy %>% 
  filter(city_state == "Baltimore, MD") %>% 
  mutate(prop = with(., prop.test(n = hom_total, x = hom_unsolved))
```

```{r}
#proportion test in R
```

